// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.linux:
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
      default:
        return web;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo9_gJQyrRjmhOnnyWMwXeWUwkCINdg8Q',
    appId: '1:40061691328:android:1fb8a674813eb20b4fd425',
    messagingSenderId: '40061691328',
    projectId: 'caltech-c6063',
    storageBucket: 'caltech-c6063.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo9_gJQyrRjmhOnnyWMwXeWUwkCINdg8Q',
    appId: '1:40061691328:web:your-web-app-id',
    messagingSenderId: '40061691328',
    projectId: 'caltech-c6063',
    authDomain: 'caltech-c6063.firebaseapp.com', // ✅ Add authDomain
    storageBucket: 'caltech-c6063.appspot.com',
  );
}
