class HealthData {
  int age;
  String gender;
  String ethnicity;
  int socioeconomicStatus;
  int educationLevel;
  double bmi;
  int smoking;
  int alcoholConsumption;
  int physicalActivity;
  int dietQuality;
  int sleepQuality;
  int familyHistoryKidneyDisease;
  int familyHistoryHypertension;
  int familyHistoryDiabetes;
  int previousAcuteKidneyInjury;
  int urinaryTractInfections;
  int systolicBP;
  int diastolicBP;
  int fastingBloodSugar;
  double hba1c;
  double serumCreatinine;
  int bunLevels;
  int gfr;
  int proteinInUrine;
  int acr;
  int serumElectrolytesSodium;
  double serumElectrolytesPotassium;
  double serumElectrolytesCalcium;
  double serumElectrolytesPhosphorus;
  double hemoglobinLevels;
  int cholesterolTotal;
  int cholesterolLDL;
  int cholesterolHDL;
  int cholesterolTriglycerides;
  int aceInhibitors;
  int diuretics;
  int statins;
  int heavyMetalsExposure;
  int occupationalExposureChemicals;
  int waterQuality;
  int medicalCheckupsFrequency;
  int medicationAdherence;
  int healthLiteracy;
  int edema;
  int fatigueLevels;
  int nauseaVomiting;
  int muscleCramps;
  int itching;
  int qualityOfLifeScore;
  int nsaisUse;
  int antidiabeticMedications;

  HealthData({
    required this.age,
    required this.gender,
    required this.ethnicity,
    required this.socioeconomicStatus,
    required this.educationLevel,
    required this.bmi,
    required this.smoking,
    required this.alcoholConsumption,
    required this.physicalActivity,
    required this.dietQuality,
    required this.sleepQuality,
    required this.familyHistoryKidneyDisease,
    required this.familyHistoryHypertension,
    required this.familyHistoryDiabetes,
    required this.previousAcuteKidneyInjury,
    required this.urinaryTractInfections,
    required this.systolicBP,
    required this.diastolicBP,
    required this.fastingBloodSugar,
    required this.hba1c,
    required this.serumCreatinine,
    required this.bunLevels,
    required this.gfr,
    required this.proteinInUrine,
    required this.acr,
    required this.serumElectrolytesSodium,
    required this.serumElectrolytesPotassium,
    required this.serumElectrolytesCalcium,
    required this.serumElectrolytesPhosphorus,
    required this.hemoglobinLevels,
    required this.cholesterolTotal,
    required this.cholesterolLDL,
    required this.cholesterolHDL,
    required this.cholesterolTriglycerides,
    required this.aceInhibitors,
    required this.diuretics,
    required this.statins,
    required this.heavyMetalsExposure,
    required this.occupationalExposureChemicals,
    required this.waterQuality,
    required this.medicalCheckupsFrequency,
    required this.medicationAdherence,
    required this.healthLiteracy,
    required this.edema,
    required this.fatigueLevels,
    required this.nauseaVomiting,
    required this.muscleCramps,
    required this.itching,
    required this.qualityOfLifeScore,
    required this.nsaisUse,
    required this.antidiabeticMedications,
  });
}
